"""Create a new unit that is conformant to every applicable rule by construction.

    ./run scaffold KIND=backend-feature  NAME=reports
    ./run scaffold KIND=frontend-feature NAME=reports

WHY THIS EXISTS. Every rule in the ledger has a fixture proving it able to fail, and there
are dozens of them. A person adding a backend feature by hand has to remember a unit registration
in `architecture.toml`, an allowed-edge list that does not accidentally grant the
Taskwarrior door, a guard declaration in `rules/route-guards.toml`, two test tiers, the
coverage floor, two public-surface snapshots, two counted claims in `AGENTS.md`, and a
`git add` early enough for the index to see the files at all. Every one of those is a place
to be right, and the failure mode of forgetting the guard declaration is the interesting
one: the route works, it just works for everybody.

So the first commit of a new unit is generated rather than remembered. What comes out is
not a template with TODOs in it — it is a working, guarded, tested, snapshotted slice that
`./run verify` passes with nothing edited by hand. Replacing what it returns is then a
normal change, with the gate already holding the shape.

WHAT IT DELIBERATELY DOES NOT DO. It does not design the feature, it does not write a
Change Impact Brief (that needs intent — `./run brief` pre-fills one), and it does not
commit. See docs/adr/0029-the-scaffold-generator.md.

Exit codes follow the interface contract: 0 ok, 2 needs input (a missing or unknown KIND or
NAME, or a unit that already exists), 3 tooling.
"""

from __future__ import annotations

import datetime as dt
import json
import os
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARCHITECTURE = ROOT / "architecture.toml"
ROUTE_GUARDS = ROOT / "rules" / "route-guards.toml"
CONTRACT = ROOT / "AGENTS.md"
MAIN = ROOT / "backend" / "app" / "main.py"
SPA_ROUTER = ROOT / "frontend" / "src" / "router" / "index.js"
BASELINE = ROOT / "ops" / "structure-baseline.toml"

EX_OK, EX_NEEDS_INPUT, EX_TOOLING = 0, 2, 3

KINDS = ("backend-feature", "frontend-feature")

# One lowercase word, or several joined by underscores. Narrow on purpose: the same string
# becomes a Python module name, a URL path segment, a unit id, a pytest file name and a Vue
# component prefix, and the set of strings that is safe in all five is exactly this one.
NAME_PATTERN = re.compile(r"^[a-z][a-z0-9]*(_[a-z0-9]+)*$")

UNIT_MARKER = "# <<< generated feature units"
EDGE_MARKER = "# <<< generated feature edges"


class NeedsInput(Exception):
    """A required value is missing or unusable — exit 2, naming what and how to supply it."""


class Tooling(Exception):
    """A prerequisite is missing or a repository command failed — exit 3."""


# --- naming -------------------------------------------------------------------


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def title(name: str) -> str:
    return name.replace("_", " ").capitalize()


def render(template: str, name: str) -> str:
    """Fill a template. Placeholders are `@NAME@`-shaped so that nothing in the generated
    Python, Vue or TOML has to be escaped to survive being a template."""
    return (
        template.replace("@PASCAL@", pascal(name))
        .replace("@TITLE_LOWER@", title(name).lower())
        .replace("@TITLE@", title(name))
        .replace("@NAME@", name)
    )


# --- templates ----------------------------------------------------------------

BACKEND_MODELS = '''"""The shapes the @TITLE_LOWER@ feature speaks in.

Generated by `./run scaffold KIND=backend-feature NAME=@NAME@`. They live beside
app/models.py rather than inside it: that file is the shared DTO kernel every router
depends on, and it is allowlisted as a hub for exactly that reason. A shape becomes shared
when a second unit needs it, which is a move somebody makes on purpose.
"""

from pydantic import BaseModel


class @PASCAL@Item(BaseModel):
    """One row of whatever this feature lists."""

    label: str
    detail: str = ""


class @PASCAL@Summary(BaseModel):
    """What `GET /@NAME@` answers with."""

    feature: str
    username: str
    items: list[@PASCAL@Item] = []
'''

BACKEND_SERVICE = '''"""What the @TITLE_LOWER@ feature does, with no HTTP in it.

Generated by `./run scaffold KIND=backend-feature NAME=@NAME@`. The split from the router is
the point: the router translates a request into a call and a result into a response, and
this file translates nothing. It is also what lets the logic be tested without a client.

A task operation never belongs here. Taskwarrior has one door — be/adapters/task, reached
through app/services/task_service.py — and architecture.toml does not grant this unit that
edge, so importing task_runner fails the gate rather than the review.
"""

from app.@NAME@_models import @PASCAL@Item, @PASCAL@Summary

FEATURE = "@NAME@"


def summarise(username: str) -> @PASCAL@Summary:
    """Describe the feature for one principal.

    A placeholder with a real shape rather than a `pass`: the route returns it, both test
    tiers pin it and the OpenAPI snapshot records it, so replacing it shows up as a
    behaviour change in a diff instead of as the first real line appearing in an empty file.
    """
    items = [@PASCAL@Item(label=FEATURE, detail="replace this with the feature's own data")]
    return @PASCAL@Summary(feature=FEATURE, username=username, items=items)
'''

BACKEND_ROUTER = '''"""HTTP surface for the @TITLE_LOWER@ feature.

Generated by `./run scaffold KIND=backend-feature NAME=@NAME@`. The route below is real, not
a placeholder: it is guarded, declared in rules/route-guards.toml, present in both
public-surface snapshots and covered in both test tiers. Changing its path or its handler
name is a public-surface change — the MCP tool name is derived from the handler — and the
gate will say so.

This module stays thin. Anything that is not a translation between HTTP and a call belongs
in app/services/@NAME@_service.py.
"""

import logging

from fastapi import APIRouter, Depends

from app.@NAME@_models import @PASCAL@Summary
from app.dependencies import get_current_user
from app.services import @NAME@_service

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/@NAME@", tags=["@NAME@"])


@router.get(
    "",
    response_model=@PASCAL@Summary,
    summary="@TITLE@ summary",
    description="Describe the @TITLE_LOWER@ feature for the authenticated user.",
)
def @NAME@_summary(username: str = Depends(get_current_user)) -> @PASCAL@Summary:
    summary = @NAME@_service.summarise(username)
    logger.info("@NAME@ summarised", extra={"username": username, "items": len(summary.items)})
    return summary
'''

BACKEND_UNIT_TEST = '''"""Tests for the @TITLE_LOWER@ feature.

Generated by `./run scaffold KIND=backend-feature NAME=@NAME@`. They cover the whole slice
the scaffold emits — the logic directly, the route through the client — which is what keeps
a new unit from pushing total coverage under its floor on the day it lands.

They stop being true the moment `summarise()` returns something real, and that is why they
are written now: the first behaviour change to this feature has to edit a test, in the diff,
where somebody can see it.
"""

from app.@NAME@_models import @PASCAL@Summary
from app.services import @NAME@_service


class TestSummarise:
    def test_describes_the_feature_for_the_named_principal(self):
        summary = @NAME@_service.summarise("alice")
        assert summary.feature == "@NAME@"
        assert summary.username == "alice"

    def test_answers_with_the_declared_model(self):
        assert isinstance(@NAME@_service.summarise("alice"), @PASCAL@Summary)

    def test_every_item_carries_a_label(self):
        assert all(item.label for item in @NAME@_service.summarise("alice").items)


class TestRoute:
    def test_answers_for_an_authenticated_user(self, client, auth):
        r = client.get("/@NAME@", headers=auth)
        assert r.status_code == 200
        assert r.json()["feature"] == "@NAME@"

    def test_reports_the_authenticated_principal(self, client, auth, registered):
        body = client.get("/@NAME@", headers=auth).json()
        assert body["username"] == registered["username"]

    def test_requires_authentication(self, client, registered):
        assert client.get("/@NAME@").status_code == 401
'''

BACKEND_CONTAINER_TEST = '''"""Container-tier coverage for the @TITLE_LOWER@ feature.

Generated by `./run scaffold KIND=backend-feature NAME=@NAME@`. The unit tier fakes
Taskwarrior at the ``task_runner._run`` seam; this tier runs inside
``backend/Dockerfile.test``, against the real binary and the real installed dependency set.

What it proves for a *generated* feature is deliberately narrow, because a generated feature
does nothing a fake could hide: the module is in the shipped image and the application still
assembles with the route mounted. That is not nothing — a router importing something the
runtime image does not install passes every check on a developer's machine and fails on the
first container that starts. Assertions that need the real binary go here as the feature
grows one.
"""

from __future__ import annotations

import pytest

from app.services import @NAME@_service

pytestmark = pytest.mark.container


def test_the_feature_module_is_present_in_the_image():
    assert @NAME@_service.summarise("alice").feature == "@NAME@"


def test_the_route_is_mounted_on_the_application():
    from app.main import app

    assert "/@NAME@" in {getattr(route, "path", "") for route in app.routes}
'''

BACKEND_UNIT_BLOCK = '''[[units]]
id = "be/feature/@NAME@"
scope = "backend"
layer = 1
owner = "maintainer"
paths = [
  "backend/app/routers/@NAME@.py",
  "backend/app/services/@NAME@_service.py",
  "backend/app/@NAME@_models.py",
]
note = """
Generated by `./run scaffold KIND=backend-feature NAME=@NAME@`. A vertical slice: the router
that exposes the feature, the logic behind it, and the shapes it speaks in. It enters at the
router layer, which is what `layer = 1` records.

The edge list is the reason this is a unit at all. It grants what a feature legitimately
needs — the injected dependencies, the database adapter, the leaves and the shared services
— and withholds be/adapters/task, so this feature cannot reach the Taskwarrior subprocess
except through be/services, where the validation lives.

What the boundary checker does NOT see is the router/service split inside the slice: both
files are in one unit, so an import between them is internal. That split is held by review
and by the module docstrings, not by the gate.
"""

'''

BACKEND_EDGE_BLOCK = '''[[allowed_edges]]
from = "be/feature/@NAME@"
to = ["be/services", "be/adapters/db", "be/di", "be/leaves"]
note = "Generated. be/adapters/task is withheld on purpose — see the unit's note."

'''

FRONTEND_LOGIC = """/**
 * The @TITLE_LOWER@ feature's logic, kept out of its component.
 *
 * Generated by `./run scaffold KIND=frontend-feature NAME=@NAME@`. It is pure — no Vue, no
 * store, no network — which is what makes it directly testable, and the frontend tier tests
 * exactly this kind of module (ADR 0007). Rendering, routing and gestures are deliberately
 * untested here (`RISK-TEST-004`), so logic that matters belongs in this file rather than in
 * the view next to it.
 */

/** The feature's name, as the route path and the view heading use it. */
export const FEATURE = '@NAME@'

/**
 * The rows the view renders, normalised.
 *
 * Trims each label and drops the entries that are left with nothing to show — the same
 * defensive shape `src/shared/` uses, because the data a view receives has usually been
 * through a network and a store before it arrives.
 *
 * @param {Array<{label?: string, detail?: string}>} source
 * @returns {Array<{label: string, detail: string}>}
 */
export function visibleItems(source = []) {
  return source
    .map((entry) => ({
      label: String(entry?.label ?? '').trim(),
      detail: String(entry?.detail ?? '').trim(),
    }))
    .filter((entry) => entry.label)
}

/**
 * What the view binds to.
 *
 * Returns plain values rather than refs: the generated feature has no state yet, and a `ref`
 * nothing writes to is a reactivity claim the code does not make. Introduce `ref` here when
 * something actually changes.
 *
 * @param {Array<{label?: string, detail?: string}>} source
 */
export function use@PASCAL@(source = []) {
  return { feature: FEATURE, items: visibleItems(source) }
}
"""

FRONTEND_VIEW = """<template>
  <AppShell>
    <div class="flex flex-col h-full">
      <header class="px-4 py-3 border-b bg-white dark:bg-gray-800 dark:border-gray-700">
        <h2 class="text-lg font-bold text-gray-900 dark:text-white">@TITLE@</h2>
        <p class="text-xs text-gray-400 dark:text-gray-500">Generated by make scaffold — replace this view with the feature.</p>
      </header>
      <div class="flex-1 overflow-y-auto">
        <p v-if="!items.length" class="p-4 text-sm text-gray-400 dark:text-gray-500">Nothing here yet.</p>
        <ul v-else>
          <li v-for="item in items" :key="item.label" class="px-4 py-2 border-b dark:border-gray-700 text-sm text-gray-900 dark:text-white">
            {{ item.label }}
            <span v-if="item.detail" class="text-gray-400 dark:text-gray-500">— {{ item.detail }}</span>
          </li>
        </ul>
      </div>
    </div>
  </AppShell>
</template>

<script setup>
import AppShell from '../components/AppShell.vue'
import { use@PASCAL@ } from './_use@PASCAL@.js'

const { items } = use@PASCAL@([{ label: '@NAME@', detail: 'replace this with the feature\\'s own data' }])
</script>
"""

FRONTEND_TEST = """import { describe, expect, it } from 'vitest'

import { FEATURE, use@PASCAL@, visibleItems } from '../src/views/_use@PASCAL@.js'

/**
 * Generated by `./run scaffold KIND=frontend-feature NAME=@NAME@`. They pin the pure half of
 * the feature, which is the half this repository tests (ADR 0007) and the half where every
 * frontend defect it has shipped actually was.
 */

describe('visibleItems', () => {
  it('returns nothing for an empty source', () => {
    expect(visibleItems()).toEqual([])
  })

  it('trims the label and the detail', () => {
    expect(visibleItems([{ label: '  a  ', detail: '  b  ' }])).toEqual([{ label: 'a', detail: 'b' }])
  })

  it('drops an entry with no label left after trimming', () => {
    expect(visibleItems([{ label: '   ' }, { label: 'kept' }])).toEqual([{ label: 'kept', detail: '' }])
  })

  it('tolerates a missing entry rather than throwing', () => {
    expect(visibleItems([null, { label: 'kept' }])).toEqual([{ label: 'kept', detail: '' }])
  })
})

describe('use@PASCAL@', () => {
  it('names the feature', () => {
    expect(use@PASCAL@().feature).toBe(FEATURE)
  })

  it('exposes the normalised items', () => {
    expect(use@PASCAL@([{ label: 'one' }]).items).toEqual([{ label: 'one', detail: '' }])
  })
})
"""

FRONTEND_UNIT_BLOCK = '''[[units]]
id = "fe/@NAME@"
scope = "frontend"
owner = "maintainer"
paths = [
  "frontend/src/views/@PASCAL@View.vue",
  "frontend/src/views/_use@PASCAL@.js",
]
note = """
Generated by `./run scaffold KIND=frontend-feature NAME=@NAME@`. Declared, not foldered, like
every other frontend unit: the map lives here over the existing directories.

Features never import features, so the edge list grants fe/shared and fe/layout and nothing
else. Reaching into another feature's store is the shape that produced CYCLE-001 and
CYCLE-002, and a new cycle always fails.
"""

'''

FRONTEND_EDGE_BLOCK = '''[[allowed_edges]]
from = "fe/@NAME@"
to = ["fe/shared", "fe/layout"]
note = "Generated. Features never import features."

'''


# --- file helpers -------------------------------------------------------------


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def edit(path: Path, transform) -> None:
    text = path.read_text(encoding="utf-8")
    path.write_text(transform(text), encoding="utf-8")


def insert_before_marker(text: str, marker: str, block: str) -> str:
    if marker not in text:
        raise Tooling(f"architecture.toml has lost its `{marker}` marker")
    return text.replace(marker, block + marker, 1)


def grant_edge(text: str, source_unit: str, target_unit: str) -> str:
    """Add one unit id to an existing allowed_edges entry's `to` list."""
    pattern = re.compile(
        r'(\[\[allowed_edges\]\]\nfrom = "' + re.escape(source_unit) + r'"\nto = \[)([^\]]*)(\])'
    )
    match = pattern.search(text)
    if not match:
        raise Tooling(f"architecture.toml has no allowed_edges entry for `{source_unit}`")
    if f'"{target_unit}"' in match.group(2):
        return text
    return text[: match.end(2)] + f', "{target_unit}"' + text[match.end(2) :]


def declared_units() -> set[str]:
    with open(ARCHITECTURE, "rb") as fh:
        return {unit["id"] for unit in tomllib.load(fh)["units"]}


# --- the two kinds ------------------------------------------------------------


def backend_feature(name: str) -> tuple[list[Path], list[Path]]:
    created = {
        ROOT / "backend" / "app" / f"{name}_models.py": BACKEND_MODELS,
        ROOT / "backend" / "app" / "services" / f"{name}_service.py": BACKEND_SERVICE,
        ROOT / "backend" / "app" / "routers" / f"{name}.py": BACKEND_ROUTER,
        ROOT / "backend" / "tests" / "unit" / f"test_{name}.py": BACKEND_UNIT_TEST,
        ROOT / "backend" / "tests" / "container" / f"test_{name}.py": BACKEND_CONTAINER_TEST,
    }
    refuse_if_present(created, f"be/feature/{name}")

    for path, template in created.items():
        write(path, render(template, name))

    edit(ARCHITECTURE, lambda t: architecture_for_backend(t, name))
    edit(ROUTE_GUARDS, lambda t: declare_guard(t, f"GET /{name}"))
    edit(MAIN, lambda t: mount_router(t, name))
    edit(CONTRACT, lambda t: bump_surface_counts(t, 1))

    return list(created), [ARCHITECTURE, ROUTE_GUARDS, MAIN, CONTRACT]


def architecture_for_backend(text: str, name: str) -> str:
    text = insert_before_marker(text, UNIT_MARKER, render(BACKEND_UNIT_BLOCK, name))
    text = insert_before_marker(text, EDGE_MARKER, render(BACKEND_EDGE_BLOCK, name))
    text = grant_edge(text, "be/app", f"be/feature/{name}")
    return grant_edge(text, "tests", f"be/feature/{name}")


def frontend_feature(name: str) -> tuple[list[Path], list[Path]]:
    views = ROOT / "frontend" / "src" / "views"
    created = {
        views / f"_use{pascal(name)}.js": FRONTEND_LOGIC,
        views / f"{pascal(name)}View.vue": FRONTEND_VIEW,
        ROOT / "frontend" / "tests" / f"{name}.test.js": FRONTEND_TEST,
    }
    refuse_if_present(created, f"fe/{name}")

    for path, template in created.items():
        write(path, render(template, name))

    edit(ARCHITECTURE, lambda t: architecture_for_frontend(t, name))
    edit(SPA_ROUTER, lambda t: mount_view(t, name))

    return list(created), [ARCHITECTURE, SPA_ROUTER]


def architecture_for_frontend(text: str, name: str) -> str:
    text = insert_before_marker(text, UNIT_MARKER, render(FRONTEND_UNIT_BLOCK, name))
    text = insert_before_marker(text, EDGE_MARKER, render(FRONTEND_EDGE_BLOCK, name))
    text = grant_edge(text, "fe/app", f"fe/{name}")
    return grant_edge(text, "tests", f"fe/{name}")


def refuse_if_present(created: dict[Path, str], unit_id: str) -> None:
    """Never overwrite. A scaffold that clobbers is worse than one that refuses, because the
    thing it clobbers is somebody's work and the generator looks like it succeeded."""
    if unit_id in declared_units():
        raise NeedsInput(
            f"architecture.toml already declares `{unit_id}`. "
            "Pick another NAME, or remove the existing unit first."
        )
    for path in created:
        if path.exists():
            raise NeedsInput(
                f"{path.relative_to(ROOT)} already exists. "
                "Pick another NAME, or remove the existing files first."
            )


# --- edits to hand-written files ----------------------------------------------


def declare_guard(text: str, route: str) -> str:
    """Insert a guard declaration, keeping rules/route-guards.toml in its sorted order."""
    block = f'[[routes]]\nroute = "{route}"\nguard = "user"\n\n'
    method, path = route.split(" ", 1)
    for match in re.finditer(r'^\[\[routes\]\]\nroute = "(\S+) (\S+)"$', text, re.MULTILINE):
        if (match.group(2), match.group(1)) > (path, method):
            return text[: match.start()] + block + text[match.start() :]
    return text.rstrip("\n") + "\n\n" + block.rstrip("\n") + "\n"


def mount_router(text: str, name: str) -> str:
    """Import the router in backend/app/main.py and include it."""
    imports = re.search(r"^from app\.routers import (.+)$", text, re.MULTILINE)
    if not imports:
        raise Tooling("backend/app/main.py does not import app.routers the expected way")
    modules = sorted([*(m.strip() for m in imports.group(1).split(",")), name])
    text = text[: imports.start()] + f"from app.routers import {', '.join(modules)}" + text[imports.end() :]

    includes = list(re.finditer(r"^app\.include_router\(\w+\.router\)$", text, re.MULTILINE))
    if not includes:
        raise Tooling("backend/app/main.py includes no routers")
    last = includes[-1]
    return text[: last.end()] + f"\napp.include_router({name}.router)" + text[last.end() :]


def mount_view(text: str, name: str) -> str:
    """Import the view in frontend/src/router/index.js and give it a route."""
    view = f"{pascal(name)}View"
    imports = list(re.finditer(r"^import \w+ from '\.\./views/\w+\.vue'$", text, re.MULTILINE))
    if not imports:
        raise Tooling("frontend/src/router/index.js imports no views")
    last = imports[-1]
    text = text[: last.end()] + f"\nimport {view} from '../views/{view}.vue'" + text[last.end() :]

    start = text.find("const routes = [")
    end = text.find("\n]", start)
    if start < 0 or end < 0:
        raise Tooling("frontend/src/router/index.js has no routes array")
    return text[:end] + f"\n  {{ path: '/{name}', component: {view} }}," + text[end:]


def bump_surface_counts(text: str, added: int) -> str:
    """AGENTS.md states how many REST routes and MCP tools exist, and RULE-DOC-001 checks
    both against the index. A new route moves both numbers."""
    for pattern in (r"REST API \((\d+) routes\)", r"MCP tools \((\d+)\)"):
        match = re.search(pattern, text)
        if not match:
            raise Tooling(f"AGENTS.md no longer states a count matching /{pattern}/")
        new = str(int(match.group(1)) + added)
        text = text[: match.start(1)] + new + text[match.end(1) :]
    return text


# --- finishing the job --------------------------------------------------------


def run(*command: str, why: str) -> None:
    result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True)
    if result.returncode != 0:
        raise Tooling(f"{why} failed:\n{result.stdout}{result.stderr}")


def stage(paths: list[Path]) -> None:
    """`git add` what was generated.

    Not a convenience. The index reads `git ls-files`, so an untracked file does not exist
    as far as ownership, boundaries and the counted contract claims are concerned — and a
    local `verify` would then pass on a tree CI fails on.
    """
    run("git", "add", "--", *[str(p.relative_to(ROOT)) for p in paths], why="git add")


def actually_changed(paths: list[Path]) -> list[Path]:
    """Of the files handed to the snapshot writer, the ones it really rewrote.

    `./run surfaces --update` writes all five snapshots; a backend feature moves two of them
    and a frontend feature one. Reporting the other three as modified would be a small lie in
    the one place a reader is deciding what to review.
    """
    result = subprocess.run(
        ["git", "diff", "--cached", "--name-only"], cwd=ROOT, capture_output=True, text=True
    )
    changed = set(result.stdout.split())
    return [p for p in paths if str(p.relative_to(ROOT)) in changed]


def absorb_hub_growth(command: str) -> bool:
    """Raise the fan-in baseline for whatever the new unit legitimately depends on.

    A guarded route imports `get_current_user`, so every backend feature adds one dependent
    to the auth choke point; a view wraps itself in `AppShell`, so every frontend feature
    adds one there. `RULE-ARCH-003` is a ratchet and it fires on exactly that.

    Raising it here is not the rule being evaded. The rule forbids a hub growing SILENTLY,
    and this is the opposite of silent: the new number lands in the diff with the line below
    naming the command that moved it and the date it moved, for the same review as any
    hand-written raise. Allowlisting the file instead was the alternative and it is worse —
    it would remove the signal permanently, for every future dependent, including the ones
    that are not a new route at all.
    """
    result = subprocess.run(
        ["python3", "tools/index/boundaries.py"], cwd=ROOT, capture_output=True, text=True
    )
    if result.returncode != 0:
        raise Tooling(f"the boundary report could not run:\n{result.stderr}")
    regressions = json.loads(result.stdout)["hub_regressions"]
    if not regressions:
        return False

    text = BASELINE.read_text(encoding="utf-8")
    today = dt.date.today().isoformat()
    for regression in regressions:
        note = (
            f"# Raised from {regression['baseline']} on {today} by\n"
            f"# `{command}`: the generated unit is one more dependent\n"
            "# on a file that is depended on by design. A generator raising a ratchet is still a\n"
            "# ratchet being raised — it is in this diff, and it reviews like any other line.\n"
        )
        entry = f'"{regression["file"]}" = '
        pattern = re.compile("^" + re.escape(entry) + r"\d+$", re.MULTILINE)
        replacement = f"{note}{entry}{regression['fan_in']}"
        if pattern.search(text):
            text = pattern.sub(lambda _m: replacement, text, count=1)
        else:
            text = text.replace("[hubs]\n", f"[hubs]\n{replacement}\n", 1)
    BASELINE.write_text(text, encoding="utf-8")
    return True


def finish(created: list[Path], modified: list[Path], command: str) -> list[Path]:
    """Leave the repository in the state `./run verify` expects, in the order that works.

    fix first (ruff and eslint may rewrite what was just written), then the snapshots (which
    boot the application, so they need the router already mounted), then the index, because
    every step before it changed a tracked file — and then the fan-in baseline, which can
    only be measured once the index has seen the new imports.
    """
    paths = created + modified
    stage(paths)
    run("tools/fix.sh", why="make fix")
    run(
        "backend/.venv/bin/python",
        "tools/surfaces.py",
        "--update",
        why="./run surfaces --update",
    )
    paths += sorted((ROOT / "ops" / "surfaces").glob("*"))
    stage(paths)
    run("python3", "tools/index/build.py", why="./run index")

    if absorb_hub_growth(command):
        paths.append(BASELINE)
        stage(paths)
        run("python3", "tools/index/build.py", why="./run index")
    return actually_changed(paths)


# --- entry point --------------------------------------------------------------


def parse(argv: list[str]) -> tuple[str, str]:
    values = {"KIND": "", "NAME": ""}
    for arg in argv:
        key, _, value = arg.partition("=")
        if key in values:
            values[key] = value.strip()
        else:
            raise NeedsInput(f"unrecognised argument `{arg}` — expected KIND=<kind> NAME=<name>")

    if not values["KIND"]:
        raise NeedsInput("KIND is required — one of: " + ", ".join(KINDS))
    if values["KIND"] not in KINDS:
        raise NeedsInput(f"unknown KIND `{values['KIND']}` — one of: " + ", ".join(KINDS))
    if not values["NAME"]:
        raise NeedsInput("NAME is required — a lowercase word, e.g. NAME=reports")
    if not NAME_PATTERN.match(values["NAME"]):
        raise NeedsInput(
            f"NAME `{values['NAME']}` is not usable — it becomes a Python module, a URL "
            "segment, a unit id and a component name, so it must match "
            f"{NAME_PATTERN.pattern} (e.g. reports, weekly_review)"
        )
    return values["KIND"], values["NAME"]


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def unit_id(kind: str, name: str) -> str:
    return f"be/feature/{name}" if kind == "backend-feature" else f"fe/{name}"


def report(kind: str, name: str, created: list[Path], touched: list[Path]) -> None:
    made = [rel(p) for p in created]
    changed = sorted({rel(p) for p in touched} - set(made))
    if os.environ.get("RUNWAY_JSON") == "1":
        print(
            json.dumps(
                {
                    "command": "scaffold",
                    "status": "ok",
                    "kind": kind,
                    "name": name,
                    "unit": unit_id(kind, name),
                    "created": made,
                    "modified": changed,
                }
            )
        )
        return

    print(f"scaffolded {unit_id(kind, name)} ({kind})\n")
    print("  created")
    for path in made:
        print(f"    {path}")
    print("\n  modified")
    for path in changed:
        print(f"    {path}")
    print("\nEverything above is staged. Next:")
    print("  ./run verify          # green with no manual edits — that is the point")
    print("  ./run brief           # the brief needs your intent; the scaffold has none")
    print("\nRemoving it again: docs/task-interface.md#make-scaffold")


def main(argv: list[str]) -> int:
    try:
        kind, name = parse(argv)
        if not (ROOT / "backend" / ".venv" / "bin" / "python").exists():
            raise Tooling("backend/.venv is missing — run make bootstrap")
        created, modified = (backend_feature if kind == "backend-feature" else frontend_feature)(
            name
        )
        touched = finish(created, modified, f"./run scaffold KIND={kind} NAME={name}")
    except NeedsInput as e:
        print(f"scaffold: {e}", file=sys.stderr)
        print("\n  ./run scaffold KIND=backend-feature NAME=reports", file=sys.stderr)
        print("  ./run scaffold KIND=frontend-feature NAME=reports", file=sys.stderr)
        return EX_NEEDS_INPUT
    except Tooling as e:
        print(f"scaffold: {e}", file=sys.stderr)
        return EX_TOOLING
    report(kind, name, created, touched)
    return EX_OK


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
